version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  all:
    image: aznu/ticket
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_ADDRESS: kafka:9092
      TICKET_SERVICE_TYPE: All