version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gateway:
    image: aznu/ticket
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_ADDRESS: kafka:9092
      TICKET_SERVICE_TYPE: Gateway
  ticket:
    image: aznu/ticket
    depends_on:
      - kafka
    environment:
      KAFKA_ADDRESS: kafka:9092
      TICKET_SERVICE_TYPE: Ticket
  payment:
    image: aznu/ticket
    depends_on:
      - kafka
    environment:
      KAFKA_ADDRESS: kafka:9092
      TICKET_SERVICE_TYPE: Payment
  web:
    image: aznu/web
    ports:
      - "8082:8082"
    depends_on:
      - gateway
#  all:
#    image: aznu/ticket
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_ADDRESS: kafka:9092
#      TICKET_SERVICE_TYPE: All